services:
    insta_parser.operation.post.update.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.post.update.collection.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.post.update.collection.service:
        class: InstaParserBundle\Internal\Service\ProcessCollection
        arguments:
            - '@insta_parser.operation.post.update.service'
            - '@insta_parser.operation.post.update.request_factory'
            - 'setLocation'
            - '@logger'

    insta_parser.operation.post.update.service:
        class: InstaParserBundle\Internal\Service\UpdateWithRemoteCall
        arguments:
            - '@insta_parser.operation.post.update.remote_call'
            - '@insta_parser.operation.post.update.data_updater'
            - '@logger'

    insta_parser.operation.post.update.data_updater:
        class: InstaParserBundle\Operation\Post\Update\DataUpdater\DataUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.post.update.remote_call:
        class: InstaParserBundle\Interaction\RemoteCall\RemoteCall
        arguments:
            - '@insta_parser.operation.post.update.request_assembler'
            - '@guzzle.client'
            - '@insta_parser.operation.post.update.data_extractor'
            - '@insta_parser.jms.object_builder'
            - '@insta_parser.operation.post.update.response_factory'
            - '@validator'
            - '@logger'

    insta_parser.operation.post.update.request_assembler:
        class: InstaParserBundle\Operation\Post\Update\Assembler\Assembler
        arguments:
            - ''
            - ''

    insta_parser.operation.post.update.data_extractor:
        class: Pizzamanblabla\DataTransformerBundle\DataExtractor\SearchNodes
        arguments:
            - '@insta_parser.operation.post.update.data_extractor.http_response_to_array'
            -
                - 'biography'
                - 'followed_by'
                - 'follows'

    insta_parser.operation.post.update.data_extractor.http_response_to_array:
        class: InstaParserBundle\DataExtractor\Response\Content
        arguments:
            - '@insta_parser.operation.post.update.data_extractor.json_from_html'

    insta_parser.operation.post.update.data_extractor.json_from_html:
        class: Pizzamanblabla\DataTransformerBundle\DataExtractor\RegExp
        arguments:
            - '@pizzamanblabla.data_transformer.payload_modifier.json'
            - '@insta_parser.operation.post.update.subscriber.sanitizer'
            - '/{".+;/ui'

    insta_parser.operation.post.update.subscriber.sanitizer:
        class: Pizzamanblabla\DataTransformerBundle\Sanitizer\Sanitizer
        arguments:
            -
                - ';'

    insta_parser.operation.post.update.response_factory:
        class: InstaParserBundle\Operation\Post\Update\Dto\Response\ResponseFactory

    insta_parser.operation.post.update.request_factory:
        class: InstaParserBundle\Operation\Post\Update\Dto\Request\RequestFactory