services:
    insta_parser.command.subscriber.add:
        class: InstaParserBundle\Command\Subscriber\Add
        arguments:
            - '@insta_parser.operation.subscriber.add.transactional'
            - '@logger'
        tags:
            - { name: console.command }

    insta_parser.command.parse:
        class: InstaParserBundle\Command\Mention\Update
        arguments:
            - '@insta_parser.operation.statistic.update.lock_subscribers'
            - '@insta_parser.repository_factory'
            - '@logger'
        tags:
                - { name: console.command }