services:
    insta_parser.operation.statistic.get.service:
        class: InstaParserBundle\Operation\Statistics\Get\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.subscriber.add.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.subscriber.add.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.subscriber.add.service:
        class: InstaParserBundle\Operation\Subscriber\Add\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.statistic.update.lock_subscribers:
        class: InstaParserBundle\Operation\Statistics\Update\Collection\Service\LockSubscribers
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@insta_parser.operation.statistic.update.transactional'
            - '@logger'

    insta_parser.operation.statistic.update.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.statistic.update.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.statistic.update.service:
        class: InstaParserBundle\Operation\Statistics\Update\Collection\Service\Service
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.service'
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.service:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\Service\Service
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.remote_call'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.remote_call:
        class: InstaParserBundle\Interaction\RemoteCall\RemoteCall
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.request_assembler'
            - '@guzzle.client'
            - '@insta_parser.operation.statistic.subscriber.update.data_extractor'
            - '@insta_parser.jms.object_builder'
            - '@insta_parser.operation.statistic.subscriber.update.response_factory'
            - '@validator'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.request_assembler:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\Assembler\Assembler

    insta_parser.operation.statistic.subscriber.update.data_extractor:
        class: InstaParserBundle\DataExtractor\SearchNodes
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.data_extractor.http_response_to_array'
            -
                - 'nodes'

    insta_parser.operation.statistic.subscriber.update.data_extractor.http_response_to_array:
        class: InstaParserBundle\DataExtractor\Response\Content
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.data_extractor.json_from_html'

    insta_parser.operation.statistic.subscriber.update.data_extractor.json_from_html:
        class: InstaParserBundle\DataExtractor\RegExp
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.data_extractor.payload_modifier.json'
            - '@insta_parser.operation.statistic.subscriber.update.sanitizer'
            - '/{".+;/ui'

    insta_parser.operation.statistic.subscriber.update.sanitizer:
        class: InstaParserBundle\Internal\Sanitizer\Sanitizer
        arguments:
            -
                - ';'

    insta_parser.operation.statistic.subscriber.update.data_extractor.payload_modifier.json:
        class: InstaParserBundle\PayloadModifier\Json

    insta_parser.operation.statistic.subscriber.update.response_factory:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\Dto\Response\SuccessfulResponseFactory

    #Repository Factory
    insta_parser.repository_factory:
        class: InstaParserBundle\Entity\Repository\Factory
        arguments:
            - '@doctrine.orm.entity_manager'

    #Http client
    guzzle.client:
        class: GuzzleHttp\Client

    #Object builder
    insta_parser.jms.object_builder:
        class: InstaParserBundle\Internal\ObjectBuilder\JMSObjectBuilder
        arguments:
            - '@jms_serializer'
            - '@logger'