services:
    insta_parser.operation.statistic.get.brands.service:
        class: InstaParserBundle\Operation\Statistics\Get\Brands\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.statistic.get.top.service:
        class: InstaParserBundle\Operation\Statistics\Get\Top\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.statistic.get.hashtag.service:
        class: InstaParserBundle\Operation\Statistics\Get\Hashtag\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            -
                - '#—èworldclass'
                - '#worldclassclubs'
            - '%insta_parser.clubs_locations%'
            - '@logger'

    insta_parser.operation.subscriber.add.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.subscriber.add.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.subscriber.add.service:
        class: InstaParserBundle\Operation\Subscriber\Add\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.statistic.update.lock_subscribers:
        class: InstaParserBundle\Internal\Service\Subscribers\Lock
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@insta_parser.operation.statistic.update.transactional'
            - '@logger'

    insta_parser.operation.statistic.update.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.statistic.update.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.statistic.update.service:
        class: InstaParserBundle\Internal\Service\ProcessCollection
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.service'
            - '@insta_parser.operation.subscribers.get_info.subscriber.request_factory'
            - 'setSubscriber'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.service:
        class: InstaParserBundle\Internal\Service\UpdateWithRemoteCall
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.remote_call'
            - '@insta_parser.operation.statistic.subscriber.data_updater'
            - '@insta_parser.common.data_updater.exceptional.subscriber'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.remote_call:
        class: InstaParserBundle\Interaction\RemoteCall\RemoteCall
        arguments:
            - '@insta_parser.operation.statistic.subscriber.update.request_assembler'
            - '@guzzle.client'
            - '@insta_parser.operation.statistic.subscriber.update.data_extractor'
            - '@insta_parser.jms.object_builder'
            - '@insta_parser.operation.statistic.subscriber.update.response_factory'
            - '@validator'
            - '@logger'

    insta_parser.operation.statistic.subscriber.update.request_assembler:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\Assembler\Assembler

    insta_parser.operation.statistic.subscriber.update.data_extractor:
        class: Pizzamanblabla\DataTransformerBundle\DataExtractor\SearchNodesChain
        arguments:
            - '@insta_parser.common.data_extractor.http_response_to_array'
            -
                media: 'nodes'

    insta_parser.operation.statistic.subscriber.update.response_factory:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\Dto\Response\SuccessfulResponseFactory

    insta_parser.operation.statistic.subscriber.data_updater:
        class: InstaParserBundle\Operation\Statistics\Update\Subscriber\DataUpdater\DataUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'