parameters:
    insta_parser.clubs_locations:
        -
            lat: 55.74698
            long: 37.65764

        -
            lat: 55.77362
            long: 37.60545

        -
            lat: 55.824828
            long: 37.497346

        -
            lat: 56.83232
            long: 60.61717

        -
            lat: 55.7398
            long: 37.41333

        -
            lat: 55.80511
            long: 37.39166

        -
            lat: 55.74706
            long: 37.53932

        -
            lat: 55.77401
            long: 37.58633

        -
            lat: 55.81087
            long: 37.13677

        -
            lat: 59.97481
            long: 30.25238

        -
            lat: 59.98647
            long: 30.20395

        -
            lat: 55.76182
            long: 37.6584

        -
            lat: 55.752
            long: 37.5327

        -
            lat: 59.92545
            long: 30.32165

        -
            lat: 55.69719
            long: 37.61787

        -
            lat: 55.69219
            long: 37.52769

        -
            lat: 55.804585
            long: 37.619032

        -
            lat: 55.67226
            long: 37.55939

        -
            lat: 55.76733
            long: 37.56805

        -
            lat: 55.75458
            long: 37.60947

        -
            lat: 55.72839
            long: 37.43854

        -
            lat: 55.78376
            long: 37.62519

        -
            lat: 55.66953
            long: 37.54237

        -
            lat: 55.6635
            long: 37.54979

        -
            lat: 55.74752
            long: 37.5812

        -
            lat: 55.66547
            long: 37.48653

        -
            lat: 55.744458
            long: 37.232623

        -
            lat: 55.73156
            long: 37.61582