controller.statistic:
    path: '/'
    defaults: { _controller: insta_parser.controller.statistic.metions:getMentionsAction, security: false }
    methods: [GET]

controller.statistic.pagination:
    path: '/{page}'
    defaults: { _controller: insta_parser.controller.statistic.metions:getMentionsAction, security: false }
    methods: [GET]