security:
    access_control:
        - { path: ^/, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    insta_parser:
                        password: C6pGRu7Zg5D3P2kd
                        roles: 'ROLE_ADMIN'

    firewalls:
        prod:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        dev:
            pattern: ^/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext