services:
    insta_parser.operation.subscribers.get_info.lock_subscribers:
        class: InstaParserBundle\Internal\Service\Subscribers\Lock
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@insta_parser.operation.subscribers.get_info.transactional'
            - '@logger'

    insta_parser.operation.subscribers.get_info.transactional:
        class: InstaParserBundle\Internal\Service\Transactional
        arguments:
            - '@insta_parser.operation.subscribers.get_info.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    insta_parser.operation.subscribers.get_info.service:
        class: InstaParserBundle\Internal\Service\Subscribers\ProcessCollection
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.service'
            - '@insta_parser.operation.subscribers.get_info.data_updater'
            - '@logger'

    insta_parser.operation.subscribers.get_info.data_updater:
        class: InstaParserBundle\Operation\Subscriber\GetInfo\DataUpdater\DataUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@insta_parser.repository_factory'
            - '@logger'

    insta_parser.operation.subscribers.get_info.subscriber.service:
        class: InstaParserBundle\Internal\Service\Subscriber\Service
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.remote_call'
            - '@logger'

    insta_parser.operation.subscribers.get_info.subscriber.remote_call:
        class: InstaParserBundle\Interaction\RemoteCall\RemoteCall
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.request_assembler'
            - '@guzzle.client'
            - '@insta_parser.operation.subscribers.get_info.subscriber.data_extractor'
            - '@insta_parser.jms.object_builder'
            - '@insta_parser.operation.subscribers.get_info.subscriber.response_factory'
            - '@validator'
            - '@logger'

    insta_parser.operation.subscribers.get_info.subscriber.request_assembler:
        class: InstaParserBundle\Interaction\Assembler\Subscriber\Assembler

    insta_parser.operation.subscribers.get_info.subscriber.data_extractor:
        class: InstaParserBundle\DataExtractor\SearchNodes
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.data_extractor.http_response_to_array'
            -
                - 'biography'
                - 'followed_by'
                - 'follows'

    insta_parser.operation.subscribers.get_info.subscriber.data_extractor.http_response_to_array:
        class: InstaParserBundle\DataExtractor\Response\Content
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.data_extractor.json_from_html'

    insta_parser.operation.subscribers.get_info.subscriber.data_extractor.json_from_html:
        class: InstaParserBundle\DataExtractor\RegExp
        arguments:
            - '@insta_parser.operation.subscribers.get_info.subscriber.data_extractor.payload_modifier.json'
            - '@insta_parser.operation.subscribers.get_info.subscriber.sanitizer'
            - '/{".+;/ui'

    insta_parser.operation.subscribers.get_info.subscriber.sanitizer:
        class: InstaParserBundle\Internal\Sanitizer\Sanitizer
        arguments:
            -
                - ';'

    insta_parser.operation.subscribers.get_info.subscriber.data_extractor.payload_modifier.json:
        class: InstaParserBundle\PayloadModifier\Json

    insta_parser.operation.subscribers.get_info.subscriber.response_factory:
        class: InstaParserBundle\Operation\Subscriber\GetInfo\Dto\Response\SuccessfulResponseFactory